"""Unit tests for the settings catalogue updater (scripts/update_settings.py)."""

import os
import sys

import yaml

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "files"))

import update_settings as upd
from misp_container.config import load_settings_yaml

LIVE = [
    {"setting": "MISP.baseurl", "value": "https://x", "type": "string", "level": 0, "file_only": False},
    {"setting": "MISP.new_thing", "value": False, "type": "boolean", "level": 2, "file_only": False,
     "description": "A new toggle"},
    {"setting": "Plugin.Foo_password", "value": "*****", "type": "string", "level": 2, "redacted": True, "file_only": True},
    {"setting": "MISP.live", "value": True, "type": "boolean", "level": 0},
    {"setting": "MISP.long", "value": "x", "type": "string", "level": 2, "options": {"a": 1}},
]


class TestDiff:
    def test_new_and_stale(self):
        new, stale = upd.diff(LIVE, curated={"MISP.baseurl", "MISP.gone"}, catalogue={"MISP.long"})
        assert new == ["MISP.new_thing", "Plugin.Foo_password"]
        assert stale == ["MISP.gone"]

    def test_dynamic_setting_ignored(self):
        new, stale = upd.diff(LIVE, curated={"MISP.baseurl", "MISP.new_thing", "Plugin.Foo_password", "MISP.long"}, catalogue=set())
        assert new == [] and stale == []


class TestBuildCatalogue:
    def test_entries_are_track_only_and_sorted(self):
        entries = upd.build_catalogue(LIVE, curated={"MISP.baseurl"})
        assert list(entries) == ["MISP.long", "MISP.new_thing", "Plugin.Foo_password"]
        assert entries["MISP.new_thing"] == {"value": False, "description": "A new toggle", "type": "boolean",
                                             "level": 2, "track_only": True}
        assert "description" not in entries["MISP.long"]
        secret = entries["Plugin.Foo_password"]
        assert secret["sensitive"] is True and secret["file_only"] is True and secret["value"] == ""
        assert "MISP.live" not in entries

    def test_render_round_trips(self):
        entries = upd.build_catalogue(LIVE, curated={"MISP.baseurl"})
        text = upd.render_catalogue(entries)
        assert text.startswith("# Generated by scripts/update-settings.sh")
        assert yaml.safe_load(text)["settings"] == entries


class TestEngineLoadsCatalogue:
    def test_catalogue_entries_are_track_only_and_curated_wins(self, tmp_path):
        (tmp_path / "settings.yaml").write_text(
            "settings:\n  optional:\n    MISP.baseurl:\n      value: https://curated\n")
        (tmp_path / "settings-upstream.yaml").write_text(
            "settings:\n  MISP.baseurl:\n    value: https://upstream\n    track_only: true\n"
            "  MISP.new_thing:\n    value: false\n    track_only: true\n")
        groups = load_settings_yaml(str(tmp_path / "settings.yaml"))
        assert [s.name for s in groups["optional"]] == ["MISP.baseurl"]
        assert [s.name for s in groups["upstream"]] == ["MISP.new_thing"]
        assert groups["upstream"][0].track_only is True
        assert groups["upstream"][0].kind == "bool"

    def test_no_catalogue_file(self, tmp_path):
        (tmp_path / "settings.yaml").write_text("settings:\n  optional:\n    MISP.baseurl:\n      value: x\n")
        groups = load_settings_yaml(str(tmp_path / "settings.yaml"))
        assert "upstream" not in groups
