apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
      app.kubernetes.io/name: mysql
  template:
    metadata:
      labels:
        app: mysql
        app.kubernetes.io/name: mysql
    spec:
      containers:
        - name: mariadb
          image: docker.io/library/mariadb
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --max-allowed-packet=1G
            - --innodb-buffer-pool-size=2400M
            - --innodb-read-io-threads=16
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: misp-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              value: misp
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: misp-secrets
                  key: MYSQL_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: misp-secrets
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: 200m
              memory: 2Gi
            limits:
              cpu: 4000m
              memory: 8Gi
          startupProbe:
            exec:
              command: ["healthcheck.sh", "--connect", "--innodb_initialized"]
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            exec:
              command: ["healthcheck.sh", "--connect", "--innodb_initialized"]
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["healthcheck.sh", "--connect", "--innodb_initialized"]
            periodSeconds: 30
      volumes:
        - name: mysql-data
          emptyDir:
            sizeLimit: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
spec:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  selector:
    app.kubernetes.io/name: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
