apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
spec:
  replicas: 1
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app: postgres
        app.kubernetes.io/name: postgres
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: postgres
          image: docker.io/library/postgres
          args:
            - -c
            - shared_buffers=512MB
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: misp
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: misp-db
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: misp-db
                  key: DB_PASSWORD
            - name: POSTGRES_INITDB_ARGS
              value: "--encoding=UTF8"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 4000m
              memory: 4Gi
          startupProbe:
            exec:
              command: ["pg_isready", "-U", "misp", "-d", "misp"]
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "misp", "-d", "misp"]
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "misp", "-d", "misp"]
            periodSeconds: 30
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
spec:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
