#!/usr/bin/env python3
"""Keep files/misp-config in step with the settings a live MISP knows.

Two files describe MISP settings:

  settings.yaml           curated: defaults this image applies, grouped by hand
  settings-upstream.yaml  generated: every other setting MISP defines, with MISP's
                          own default, type and level, track_only (never applied,
                          overridable through the derived env var)

    update_settings.py --check --url http://localhost:18080 --key <authkey>
    update_settings.py --write --url http://localhost:18080 --key <authkey>
    update_settings.py --write --json serverSettings.json   # a saved API response

--check exits 1 when MISP defines a setting neither file names, or when the
curated file names a setting MISP no longer defines. --write regenerates the
catalogue and reports the same two lists. scripts/update-settings.sh brings up
the Compose stack and runs this against it.
"""

import argparse
import json
import sys
import urllib.request
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
CONFIG_DIR = REPO / "files" / "misp-config"
CURATED = CONFIG_DIR / "settings.yaml"
CATALOGUE = CONFIG_DIR / "settings-upstream.yaml"

# Set by the configure step, never a default
DYNAMIC = {"MISP.live"}

HEADER = """# Generated by scripts/update-settings.sh from a live MISP: every setting MISP
# defines that settings.yaml does not name, with MISP's own default, type and
# level (0 critical, 1 recommended, 2 optional). file_only marks settings MISP
# reads from config.php only. Entries are track_only: the image never applies
# these values; they document the setting and enable its env override
# (MISP.foo -> MISP_FOO). To give a setting a default of this image, move it
# into settings.yaml.
"""


def fetch_settings(url: str, key: str) -> list[dict]:
    """The finalSettings list from /servers/serverSettings."""
    req = urllib.request.Request(
        f"{url.rstrip('/')}/servers/serverSettings",
        headers={"Authorization": key, "Accept": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=120) as resp:
        data = json.load(resp)
    return data["finalSettings"]


def curated_names(path: Path = CURATED) -> set[str]:
    with open(path) as f:
        raw = yaml.safe_load(f) or {}
    names = set()
    for group in (raw.get("settings") or {}).values():
        if isinstance(group, dict):
            names.update(group.keys())
    return names


def catalogue_names(path: Path = CATALOGUE) -> set[str]:
    if not path.exists():
        return set()
    with open(path) as f:
        raw = yaml.safe_load(f) or {}
    return set((raw.get("settings") or {}).keys())


REDACTED = "*****"


def _clean_value(value):
    """MISP returns the effective value; keep YAML-native scalars, drop the rest."""
    if value is None or value == REDACTED:
        return ""
    if isinstance(value, (bool, int, float, str)):
        return value
    return json.dumps(value)


def build_catalogue(live: list[dict], curated: set[str]) -> dict:
    """Catalogue entries for every live setting the curated file does not name.

    The API gives no descriptions; type, level (0 critical, 1 recommended,
    2 optional) and the config.php-only flag are what a reader gets.
    """
    entries = {}
    for item in live:
        name = item.get("setting")
        if not name or name in curated or name in DYNAMIC:
            continue
        entry = {"value": _clean_value(item.get("value"))}
        if item.get("type"):
            entry["type"] = item["type"]
        if item.get("level") is not None:
            entry["level"] = int(item["level"])
        if item.get("file_only"):
            entry["file_only"] = True
        if item.get("redacted") or item.get("value") == REDACTED or "password" in name.lower():
            entry["sensitive"] = True
        entry["track_only"] = True
        entries[name] = entry
    return dict(sorted(entries.items()))


def render_catalogue(entries: dict) -> str:
    body = yaml.safe_dump({"settings": entries}, sort_keys=False, allow_unicode=False, width=1000)
    return HEADER + body


def diff(live: list[dict], curated: set[str], catalogue: set[str]) -> tuple[list[str], list[str]]:
    """(new settings tracked nowhere, curated settings MISP no longer defines)."""
    live_names = {item.get("setting") for item in live if item.get("setting")}
    new = sorted(live_names - curated - catalogue - DYNAMIC)
    stale = sorted(curated - live_names - DYNAMIC)
    return new, stale


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="fail on new or stale settings")
    mode.add_argument("--write", action="store_true", help="regenerate settings-upstream.yaml")
    parser.add_argument("--url", help="MISP base URL")
    parser.add_argument("--key", help="admin API key")
    parser.add_argument("--json", help="a saved /servers/serverSettings response instead of a live MISP")
    args = parser.parse_args(argv)

    if args.json:
        with open(args.json) as f:
            live = json.load(f)["finalSettings"]
    elif args.url and args.key:
        live = fetch_settings(args.url, args.key)
    else:
        parser.error("--url and --key, or --json, are required")
    curated = curated_names()
    new, stale = diff(live, curated, catalogue_names())

    print(f"MISP settings:            {len(live)}")
    print(f"curated (settings.yaml):  {len(curated)}")
    print(f"new, tracked nowhere:     {len(new)}")
    print(f"stale in settings.yaml:   {len(stale)}")

    if stale:
        print("\nsettings.yaml names settings this MISP does not define (rename or remove them):")
        for name in stale:
            print(f"  {name}")

    if args.write:
        entries = build_catalogue(live, curated)
        CATALOGUE.write_text(render_catalogue(entries))
        print(f"\nwrote {CATALOGUE.relative_to(REPO)} with {len(entries)} settings")
        if new:
            print("added:")
            for name in new:
                print(f"  {name}")
        return 1 if stale else 0

    if new:
        print("\nsettings MISP defines that neither file names (run scripts/update-settings.sh):")
        for name in new:
            print(f"  {name}")
    if new or stale:
        return 1
    print("\nOK: every MISP setting is curated or catalogued")
    return 0


if __name__ == "__main__":
    sys.exit(main())
